# Generated by Django 3.2.25 on 2024-10-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Сотрудник платформы'), ('logistics', 'Логист'), ('accountant', 'Бухгалтер')], default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='trailer',
            field=models.CharField(max_length=100),
        ),
    ]
