# Generated by Django 3.2.25 on 2024-10-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests_handler', '0002_auto_20241005_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='logistics_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('canceled', 'Отменена')], default='Новая', max_length=50),
        ),
    ]
