# Generated by Django 3.2.25 on 2024-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_handler', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
