# Generated by Django 3.2.25 on 2024-10-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_handler', '0006_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
