# Generated by Django 3.2.25 on 2024-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_handler', '0007_errorlog_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('canceled', 'Отменена')], default='new', max_length=50),
        ),
    ]
